name: Deploy snapshot to Danubetech Nexus

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'
    branches-ignore:
      - 'release-**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run maven deploy action
        uses: danubetech/github-action-maven-deploy@master
        with:
          server_id: danubetech-maven-snapshots
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
